version: "3.8"

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./dist:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
